---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.portainer.kubernetes.application.kind: content
    io.portainer.kubernetes.application.name: tidarr
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: tidarr
    io.portainer.kubernetes.application.stackid: "3"
  name: tidarr
  namespace: default
  uid: 8b950832-c987-4dda-a627-70065e012b9e
spec:
  ports:
    - port: 8484
      targetPort: 8484
      nodePort: 30084
  selector:
    app: tidarr
  type: NodePort
status:
  loadBalancer: {}