---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.portainer.kubernetes.application.kind: content
    io.portainer.kubernetes.application.name: bazarr
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: bazarr
    io.portainer.kubernetes.application.stackid: "3"
  name: bazarr
  namespace: default
  uid: 8b950832-c987-4dda-a627-70065e012b9e
spec:
  ports:
    - port: 6767
      targetPort: 6767
      nodePort: 30067
  selector:
    app: bazarr
  type: NodePort
status:
  loadBalancer: {}